# Generated by Django 3.2.5 on 2021-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
