# Generated by Django 3.2.5 on 2021-07-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0005_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(null=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
