# Generated by Django 3.2.5 on 2021-07-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0008_alter_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, default='0', null=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
